### ISSUE TITLE
Исправление yadisk.exceptions.ResourceIsLockedError

### ISSUE THREAD

**Issue by 13adams37** [13adams37/phpErrorCrawler#11]
Traceback (most recent call last):
  File "D:\Тимофей\workdirs\!projects\phpErrorCrawler\src\uploader.py", line 31, in make_dir
    self.__client.mkdir(dir_name)
  File "C:\Python312\Lib\site-packages\yadisk\client.py", line 1136, in mkdir
    request.send()
  File "C:\Python312\Lib\site-packages\yadisk\api\api_request.py", line 161, in send
    auto_retry(self._attempt, self.n_retries, self.retry_interval)
  File "C:\Python312\Lib\site-packages\yadisk\utils.py", line 118, in auto_retry
    return func()
           ^^^^^^
  File "C:\Python312\Lib\site-packages\yadisk\api\api_request.py", line 139, in _attempt
    raise self.response.get_exception()
yadisk.exceptions.DirectoryExistsError: По указанному пути "app:/dzmo2.citrus-test.ru/" уже существует папка с таким именем. (Specified path "app:/dzmo2.citrus-test.ru/" points to existent directory. / DiskPathPointsToExistentDirectoryError)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Тимофей\workdirs\!projects\phpErrorCrawler\main.py", line 48, in <module>
    main(get_allowed_domain(args.url), [args.url])
  File "D:\Тимофей\workdirs\!projects\phpErrorCrawler\main.py", line 35, in main
    after_crawler.run(BitrixCrawler.urls_with_errors, allowed_domains[0], is_local)
  File "D:\Тимофей\workdirs\!projects\phpErrorCrawler\src\after_crawler.py", line 15, in run
    errors_with_screenshots = self.get_errors_with_screenshots(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Тимофей\workdirs\!projects\phpErrorCrawler\src\after_crawler.py", line 31, in get_errors_with_screenshots
    disk = Uploader(working_dir=working_dir)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Тимофей\workdirs\!projects\phpErrorCrawler\src\uploader.py", line 27, in __init__
    self.make_dir(self.app_path)
  File "D:\Тимофей\workdirs\!projects\phpErrorCrawler\src\uploader.py", line 35, in make_dir
    self.__client.mkdir(dir_name, n_retries = 5, retry_interval = 30)
  File "C:\Python312\Lib\site-packages\yadisk\client.py", line 1136, in mkdir
    request.send()
  File "C:\Python312\Lib\site-packages\yadisk\api\api_request.py", line 161, in send
    auto_retry(self._attempt, self.n_retries, self.retry_interval)
  File "C:\Python312\Lib\site-packages\yadisk\utils.py", line 118, in auto_retry
    return func()
           ^^^^^^
  File "C:\Python312\Lib\site-packages\yadisk\api\api_request.py", line 139, in _attempt
    raise self.response.get_exception()
yadisk.exceptions.DirectoryExistsError: По указанному пути "app:/dzmo2.citrus-test.ru/" уже существует папка с таким именем. (Specified path "app:/dzmo2.citrus-test.ru/" points to existent directory. / DiskPathPointsToExistentDirectoryError)

**Comment by 13adams37** [comment]
Traceback (most recent call last):
  File "D:\Тимофей\workdirs\!projects\phpErrorCrawler\src\uploader.py", line 31, in make_dir
    self.__client.mkdir(dir_name)
  File "C:\Python312\Lib\site-packages\yadisk\client.py", line 1136, in mkdir
    request.send()
  File "C:\Python312\Lib\site-packages\yadisk\api\api_request.py", line 161, in send
    auto_retry(self._attempt, self.n_retries, self.retry_interval)
  File "C:\Python312\Lib\site-packages\yadisk\utils.py", line 118, in auto_retry
    return func()
           ^^^^^^
  File "C:\Python312\Lib\site-packages\yadisk\api\api_request.py", line 139, in _attempt
    raise self.response.get_exception()
yadisk.exceptions.DirectoryExistsError: По указанному пути "app:/ocowork.citrus-web.ru/" уже существует папка с таким именем. (Specified path "app:/ocowork.citrus-web.ru/" points to existent directory. / DiskPathPointsToExistentDirectoryError)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Тимофей\workdirs\!projects\phpErrorCrawler\main.py", line 48, in <module>
    main(get_allowed_domain(args.url), [args.url])
  File "D:\Тимофей\workdirs\!projects\phpErrorCrawler\main.py", line 35, in main
    after_crawler.run(BitrixCrawler.urls_with_errors, allowed_domains[0], is_local)
  File "D:\Тимофей\workdirs\!projects\phpErrorCrawler\src\after_crawler.py", line 15, in run
    errors_with_screenshots = self.get_errors_with_screenshots(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Тимофей\workdirs\!projects\phpErrorCrawler\src\after_crawler.py", line 31, in get_errors_with_screenshots
    disk = Uploader(working_dir=working_dir)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Тимофей\workdirs\!projects\phpErrorCrawler\src\uploader.py", line 27, in __init__
    self.make_dir(self.app_path)
  File "D:\Тимофей\workdirs\!projects\phpErrorCrawler\src\uploader.py", line 35, in make_dir
    self.__client.mkdir(dir_name, n_retries = 5, retry_interval = 30)
  File "C:\Python312\Lib\site-packages\yadisk\client.py", line 1136, in mkdir
    request.send()
  File "C:\Python312\Lib\site-packages\yadisk\api\api_request.py", line 161, in send
    auto_retry(self._attempt, self.n_retries, self.retry_interval)
  File "C:\Python312\Lib\site-packages\yadisk\utils.py", line 118, in auto_retry
    return func()
           ^^^^^^
  File "C:\Python312\Lib\site-packages\yadisk\api\api_request.py", line 139, in _attempt
    raise self.response.get_exception()
yadisk.exceptions.ResourceIsLockedError: Ресурс заблокирован. Возможно, над ним выполняется другая операция. (Resource is locked. / DiskResourceLockedError)
